/*
Navicat MySQL Data Transfer

Source Server         : mysql_local
Source Server Version : 100406
Source Host           : localhost:3306
Source Database       : hermaya

Target Server Type    : MYSQL
Target Server Version : 100406
File Encoding         : 65001

Date: 2019-10-07 12:52:22
*/

SET FOREIGN_KEY_CHECKS=0;

-- ----------------------------
-- Table structure for admin
-- ----------------------------
DROP TABLE IF EXISTS `admin`;
CREATE TABLE `admin` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `username` varchar(255) NOT NULL,
  `password` varchar(255) NOT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=2 DEFAULT CHARSET=latin1;

-- ----------------------------
-- Records of admin
-- ----------------------------
INSERT INTO `admin` VALUES ('1', 'admin', '825e50dcdd8e270a266387c031bbca05');

-- ----------------------------
-- Table structure for berita
-- ----------------------------
DROP TABLE IF EXISTS `berita`;
CREATE TABLE `berita` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `tanggal` date DEFAULT NULL,
  `judul` varchar(255) DEFAULT NULL,
  `konten` text DEFAULT NULL,
  `image` text DEFAULT NULL,
  `aktif` int(2) DEFAULT 0,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=138 DEFAULT CHARSET=latin1;

-- ----------------------------
-- Records of berita
-- ----------------------------
INSERT INTO `berita` VALUES ('38', '1978-08-28', 'quibusdam', '<p>There are many variations of passages of Lorem Ipsum available, but the majority have suffered alteration in some form, by injected humour, or randomised words which dont look even slightly believable There are many variations of passages of Lorem Ipsum available, but the majority have suffered alteration in some form, by injected humour.</p>', '456248-apel-malang.jpg', '0');
INSERT INTO `berita` VALUES ('39', '2017-06-20', 'praesentium', '<p>There are many variations of passages of Lorem Ipsum available, but the majority have suffered alteration in some form, by injected humour, or randomised words which dont look even slightly believable There are many variations of passages of Lorem Ipsum available, but the majority have suffered alteration in some form, by injected humour.</p>', 'Koala_kumal.jpg', '0');
INSERT INTO `berita` VALUES ('40', '1978-10-14', 'aspernatur', '<p>There are many variations of passages of Lorem Ipsum available, but the majority have suffered alteration in some form, by injected humour, or randomised words which dont look even slightly believable There are many variations of passages of Lorem Ipsum available, but the majority have suffered alteration in some form, by injected humour.</p>', 'Koala_kumal.jpg', '0');
INSERT INTO `berita` VALUES ('41', '2007-11-09', 'eaque', '<p>There are many variations of passages of Lorem Ipsum available, but the majority have suffered alteration in some form, by injected humour, or randomised words which dont look even slightly believable There are many variations of passages of Lorem Ipsum available, but the majority have suffered alteration in some form, by injected humour.</p>', 'Koala_kumal.jpg', '0');
INSERT INTO `berita` VALUES ('42', '2006-01-15', 'natus', '<p>There are many variations of passages of Lorem Ipsum available, but the majority have suffered alteration in some form, by injected humour, or randomised words which dont look even slightly believable There are many variations of passages of Lorem Ipsum available, but the majority have suffered alteration in some form, by injected humour.</p>', 'Koala_kumal.jpg', '0');
INSERT INTO `berita` VALUES ('43', '2018-06-07', 'suscipit', '<p>There are many variations of passages of Lorem Ipsum available, but the majority have suffered alteration in some form, by injected humour, or randomised words which dont look even slightly believable There are many variations of passages of Lorem Ipsum available, but the majority have suffered alteration in some form, by injected humour.</p>', 'Koala_kumal.jpg', '0');
INSERT INTO `berita` VALUES ('44', '1977-11-16', 'aliquid', '<p>There are many variations of passages of Lorem Ipsum available, but the majority have suffered alteration in some form, by injected humour, or randomised words which dont look even slightly believable There are many variations of passages of Lorem Ipsum available, but the majority have suffered alteration in some form, by injected humour.</p>', 'Koala_kumal.jpg', '0');
INSERT INTO `berita` VALUES ('45', '1996-02-13', 'quos', '<p>There are many variations of passages of Lorem Ipsum available, but the majority have suffered alteration in some form, by injected humour, or randomised words which dont look even slightly believable There are many variations of passages of Lorem Ipsum available, but the majority have suffered alteration in some form, by injected humour.</p>', 'Koala_kumal.jpg', '0');
INSERT INTO `berita` VALUES ('46', '1978-05-13', 'magni', '<p>There are many variations of passages of Lorem Ipsum available, but the majority have suffered alteration in some form, by injected humour, or randomised words which dont look even slightly believable There are many variations of passages of Lorem Ipsum available, but the majority have suffered alteration in some form, by injected humour.</p>', 'Koala_kumal.jpg', '0');
INSERT INTO `berita` VALUES ('47', '1982-12-05', 'qui', '<p>There are many variations of passages of Lorem Ipsum available, but the majority have suffered alteration in some form, by injected humour, or randomised words which dont look even slightly believable There are many variations of passages of Lorem Ipsum available, but the majority have suffered alteration in some form, by injected humour.</p>', 'Koala_kumal.jpg', '0');
INSERT INTO `berita` VALUES ('48', '1984-11-08', 'nisi', '<p>There are many variations of passages of Lorem Ipsum available, but the majority have suffered alteration in some form, by injected humour, or randomised words which dont look even slightly believable There are many variations of passages of Lorem Ipsum available, but the majority have suffered alteration in some form, by injected humour.</p>', 'Koala_kumal.jpg', '0');
INSERT INTO `berita` VALUES ('49', '2009-09-11', 'iste', '<p>There are many variations of passages of Lorem Ipsum available, but the majority have suffered alteration in some form, by injected humour, or randomised words which dont look even slightly believable There are many variations of passages of Lorem Ipsum available, but the majority have suffered alteration in some form, by injected humour.</p>', 'Koala_kumal.jpg', '0');
INSERT INTO `berita` VALUES ('50', '2011-02-18', 'quam', '<p>There are many variations of passages of Lorem Ipsum available, but the majority have suffered alteration in some form, by injected humour, or randomised words which dont look even slightly believable There are many variations of passages of Lorem Ipsum available, but the majority have suffered alteration in some form, by injected humour.</p>', 'Koala_kumal.jpg', '0');
INSERT INTO `berita` VALUES ('51', '1998-10-09', 'rerum', '<p>There are many variations of passages of Lorem Ipsum available, but the majority have suffered alteration in some form, by injected humour, or randomised words which dont look even slightly believable There are many variations of passages of Lorem Ipsum available, but the majority have suffered alteration in some form, by injected humour.</p>', 'Koala_kumal.jpg', '0');
INSERT INTO `berita` VALUES ('52', '1976-10-05', 'dolor', '<p>There are many variations of passages of Lorem Ipsum available, but the majority have suffered alteration in some form, by injected humour, or randomised words which dont look even slightly believable There are many variations of passages of Lorem Ipsum available, but the majority have suffered alteration in some form, by injected humour.</p>', 'Koala_kumal.jpg', '0');
INSERT INTO `berita` VALUES ('53', '1986-03-09', 'modi', '<p>There are many variations of passages of Lorem Ipsum available, but the majority have suffered alteration in some form, by injected humour, or randomised words which dont look even slightly believable There are many variations of passages of Lorem Ipsum available, but the majority have suffered alteration in some form, by injected humour.</p>', 'Koala_kumal.jpg', '0');
INSERT INTO `berita` VALUES ('54', '1997-09-08', 'assumenda', '<p>There are many variations of passages of Lorem Ipsum available, but the majority have suffered alteration in some form, by injected humour, or randomised words which dont look even slightly believable There are many variations of passages of Lorem Ipsum available, but the majority have suffered alteration in some form, by injected humour.</p>', 'Koala_kumal.jpg', '0');
INSERT INTO `berita` VALUES ('55', '1997-03-25', 'est', '<p>There are many variations of passages of Lorem Ipsum available, but the majority have suffered alteration in some form, by injected humour, or randomised words which dont look even slightly believable There are many variations of passages of Lorem Ipsum available, but the majority have suffered alteration in some form, by injected humour.</p>', 'Koala_kumal.jpg', '0');
INSERT INTO `berita` VALUES ('56', '1984-11-27', 'et', '<p>There are many variations of passages of Lorem Ipsum available, but the majority have suffered alteration in some form, by injected humour, or randomised words which dont look even slightly believable There are many variations of passages of Lorem Ipsum available, but the majority have suffered alteration in some form, by injected humour.</p>', 'Koala_kumal.jpg', '0');
INSERT INTO `berita` VALUES ('57', '2002-02-27', 'placeat', '<p>There are many variations of passages of Lorem Ipsum available, but the majority have suffered alteration in some form, by injected humour, or randomised words which dont look even slightly believable There are many variations of passages of Lorem Ipsum available, but the majority have suffered alteration in some form, by injected humour.</p>', 'Koala_kumal.jpg', '0');
INSERT INTO `berita` VALUES ('58', '1986-12-01', 'accusantium', '<p>There are many variations of passages of Lorem Ipsum available, but the majority have suffered alteration in some form, by injected humour, or randomised words which dont look even slightly believable There are many variations of passages of Lorem Ipsum available, but the majority have suffered alteration in some form, by injected humour.</p>', 'Koala_kumal.jpg', '0');
INSERT INTO `berita` VALUES ('59', '1999-02-09', 'et', '<p>There are many variations of passages of Lorem Ipsum available, but the majority have suffered alteration in some form, by injected humour, or randomised words which dont look even slightly believable There are many variations of passages of Lorem Ipsum available, but the majority have suffered alteration in some form, by injected humour.</p>', 'Koala_kumal.jpg', '0');
INSERT INTO `berita` VALUES ('60', '2002-04-30', 'sit', '<p>There are many variations of passages of Lorem Ipsum available, but the majority have suffered alteration in some form, by injected humour, or randomised words which dont look even slightly believable There are many variations of passages of Lorem Ipsum available, but the majority have suffered alteration in some form, by injected humour.</p>', 'Koala_kumal.jpg', '0');
INSERT INTO `berita` VALUES ('61', '2005-01-19', 'ex', '<p>There are many variations of passages of Lorem Ipsum available, but the majority have suffered alteration in some form, by injected humour, or randomised words which dont look even slightly believable There are many variations of passages of Lorem Ipsum available, but the majority have suffered alteration in some form, by injected humour.</p>', 'Koala_kumal.jpg', '0');
INSERT INTO `berita` VALUES ('62', '2005-04-12', 'placeat', '<p>There are many variations of passages of Lorem Ipsum available, but the majority have suffered alteration in some form, by injected humour, or randomised words which dont look even slightly believable There are many variations of passages of Lorem Ipsum available, but the majority have suffered alteration in some form, by injected humour.</p>', 'Koala_kumal.jpg', '0');
INSERT INTO `berita` VALUES ('63', '2015-04-13', 'quidem', '<p>There are many variations of passages of Lorem Ipsum available, but the majority have suffered alteration in some form, by injected humour, or randomised words which dont look even slightly believable There are many variations of passages of Lorem Ipsum available, but the majority have suffered alteration in some form, by injected humour.</p>', 'Koala_kumal.jpg', '0');
INSERT INTO `berita` VALUES ('64', '1984-12-23', 'sit', '<p>There are many variations of passages of Lorem Ipsum available, but the majority have suffered alteration in some form, by injected humour, or randomised words which dont look even slightly believable There are many variations of passages of Lorem Ipsum available, but the majority have suffered alteration in some form, by injected humour.</p>', 'Koala_kumal.jpg', '0');
INSERT INTO `berita` VALUES ('65', '2007-09-16', 'et', '<p>There are many variations of passages of Lorem Ipsum available, but the majority have suffered alteration in some form, by injected humour, or randomised words which dont look even slightly believable There are many variations of passages of Lorem Ipsum available, but the majority have suffered alteration in some form, by injected humour.</p>', 'Koala_kumal.jpg', '0');
INSERT INTO `berita` VALUES ('66', '1971-09-14', 'non', '<p>There are many variations of passages of Lorem Ipsum available, but the majority have suffered alteration in some form, by injected humour, or randomised words which dont look even slightly believable There are many variations of passages of Lorem Ipsum available, but the majority have suffered alteration in some form, by injected humour.</p>', 'Koala_kumal.jpg', '0');
INSERT INTO `berita` VALUES ('67', '1989-10-08', 'consequuntur', '<p>There are many variations of passages of Lorem Ipsum available, but the majority have suffered alteration in some form, by injected humour, or randomised words which dont look even slightly believable There are many variations of passages of Lorem Ipsum available, but the majority have suffered alteration in some form, by injected humour.</p>', 'Koala_kumal.jpg', '0');
INSERT INTO `berita` VALUES ('68', '2011-01-28', 'quia', '<p>There are many variations of passages of Lorem Ipsum available, but the majority have suffered alteration in some form, by injected humour, or randomised words which dont look even slightly believable There are many variations of passages of Lorem Ipsum available, but the majority have suffered alteration in some form, by injected humour.</p>', 'Koala_kumal.jpg', '0');
INSERT INTO `berita` VALUES ('69', '1983-05-13', 'veritatis', '<p>There are many variations of passages of Lorem Ipsum available, but the majority have suffered alteration in some form, by injected humour, or randomised words which dont look even slightly believable There are many variations of passages of Lorem Ipsum available, but the majority have suffered alteration in some form, by injected humour.</p>', 'Koala_kumal.jpg', '0');
INSERT INTO `berita` VALUES ('70', '1998-04-24', 'quae', '<p>There are many variations of passages of Lorem Ipsum available, but the majority have suffered alteration in some form, by injected humour, or randomised words which dont look even slightly believable There are many variations of passages of Lorem Ipsum available, but the majority have suffered alteration in some form, by injected humour.</p>', 'Koala_kumal.jpg', '0');
INSERT INTO `berita` VALUES ('71', '2002-06-29', 'accusamus', '<p>There are many variations of passages of Lorem Ipsum available, but the majority have suffered alteration in some form, by injected humour, or randomised words which dont look even slightly believable There are many variations of passages of Lorem Ipsum available, but the majority have suffered alteration in some form, by injected humour.</p>', 'Koala_kumal.jpg', '0');
INSERT INTO `berita` VALUES ('72', '1999-04-15', 'consequatur', '<p>There are many variations of passages of Lorem Ipsum available, but the majority have suffered alteration in some form, by injected humour, or randomised words which dont look even slightly believable There are many variations of passages of Lorem Ipsum available, but the majority have suffered alteration in some form, by injected humour.</p>', 'Koala_kumal.jpg', '0');
INSERT INTO `berita` VALUES ('73', '2004-04-07', 'animi', '<p>There are many variations of passages of Lorem Ipsum available, but the majority have suffered alteration in some form, by injected humour, or randomised words which dont look even slightly believable There are many variations of passages of Lorem Ipsum available, but the majority have suffered alteration in some form, by injected humour.</p>', 'Koala_kumal.jpg', '0');
INSERT INTO `berita` VALUES ('74', '2005-06-20', 'qui', '<p>There are many variations of passages of Lorem Ipsum available, but the majority have suffered alteration in some form, by injected humour, or randomised words which dont look even slightly believable There are many variations of passages of Lorem Ipsum available, but the majority have suffered alteration in some form, by injected humour.</p>', 'Koala_kumal.jpg', '0');
INSERT INTO `berita` VALUES ('75', '1982-07-01', 'ullam', '<p>There are many variations of passages of Lorem Ipsum available, but the majority have suffered alteration in some form, by injected humour, or randomised words which dont look even slightly believable There are many variations of passages of Lorem Ipsum available, but the majority have suffered alteration in some form, by injected humour.</p>', 'Koala_kumal.jpg', '0');
INSERT INTO `berita` VALUES ('76', '1991-06-11', 'totam', '<p>There are many variations of passages of Lorem Ipsum available, but the majority have suffered alteration in some form, by injected humour, or randomised words which dont look even slightly believable There are many variations of passages of Lorem Ipsum available, but the majority have suffered alteration in some form, by injected humour.</p>', 'Koala_kumal.jpg', '0');
INSERT INTO `berita` VALUES ('77', '1983-08-17', 'occaecati', '<p>There are many variations of passages of Lorem Ipsum available, but the majority have suffered alteration in some form, by injected humour, or randomised words which dont look even slightly believable There are many variations of passages of Lorem Ipsum available, but the majority have suffered alteration in some form, by injected humour.</p>', 'Koala_kumal.jpg', '0');
INSERT INTO `berita` VALUES ('78', '1985-02-02', 'necessitatibus', '<p>There are many variations of passages of Lorem Ipsum available, but the majority have suffered alteration in some form, by injected humour, or randomised words which dont look even slightly believable There are many variations of passages of Lorem Ipsum available, but the majority have suffered alteration in some form, by injected humour.</p>', 'Koala_kumal.jpg', '0');
INSERT INTO `berita` VALUES ('79', '2005-04-19', 'saepe', '<p>There are many variations of passages of Lorem Ipsum available, but the majority have suffered alteration in some form, by injected humour, or randomised words which dont look even slightly believable There are many variations of passages of Lorem Ipsum available, but the majority have suffered alteration in some form, by injected humour.</p>', 'Koala_kumal.jpg', '0');
INSERT INTO `berita` VALUES ('80', '1972-12-24', 'consequatur', '<p>There are many variations of passages of Lorem Ipsum available, but the majority have suffered alteration in some form, by injected humour, or randomised words which dont look even slightly believable There are many variations of passages of Lorem Ipsum available, but the majority have suffered alteration in some form, by injected humour.</p>', 'Koala_kumal.jpg', '0');
INSERT INTO `berita` VALUES ('81', '1977-06-17', 'nam', '<p>There are many variations of passages of Lorem Ipsum available, but the majority have suffered alteration in some form, by injected humour, or randomised words which dont look even slightly believable There are many variations of passages of Lorem Ipsum available, but the majority have suffered alteration in some form, by injected humour.</p>', 'Koala_kumal.jpg', '0');
INSERT INTO `berita` VALUES ('82', '1993-09-01', 'delectus', '<p>There are many variations of passages of Lorem Ipsum available, but the majority have suffered alteration in some form, by injected humour, or randomised words which dont look even slightly believable There are many variations of passages of Lorem Ipsum available, but the majority have suffered alteration in some form, by injected humour.</p>', 'Koala_kumal.jpg', '0');
INSERT INTO `berita` VALUES ('83', '1985-11-29', 'dignissimos', '<p>There are many variations of passages of Lorem Ipsum available, but the majority have suffered alteration in some form, by injected humour, or randomised words which dont look even slightly believable There are many variations of passages of Lorem Ipsum available, but the majority have suffered alteration in some form, by injected humour.</p>', 'Koala_kumal.jpg', '0');
INSERT INTO `berita` VALUES ('84', '1988-08-23', 'provident', '<p>There are many variations of passages of Lorem Ipsum available, but the majority have suffered alteration in some form, by injected humour, or randomised words which dont look even slightly believable There are many variations of passages of Lorem Ipsum available, but the majority have suffered alteration in some form, by injected humour.</p>', 'Koala_kumal.jpg', '0');
INSERT INTO `berita` VALUES ('85', '2003-10-03', 'est', '<p>There are many variations of passages of Lorem Ipsum available, but the majority have suffered alteration in some form, by injected humour, or randomised words which dont look even slightly believable There are many variations of passages of Lorem Ipsum available, but the majority have suffered alteration in some form, by injected humour.</p>', 'Koala_kumal.jpg', '0');
INSERT INTO `berita` VALUES ('86', '1970-02-11', 'molestiae', '<p>There are many variations of passages of Lorem Ipsum available, but the majority have suffered alteration in some form, by injected humour, or randomised words which dont look even slightly believable There are many variations of passages of Lorem Ipsum available, but the majority have suffered alteration in some form, by injected humour.</p>', 'Koala_kumal.jpg', '0');
INSERT INTO `berita` VALUES ('87', '1977-10-09', 'maxime', '<p>There are many variations of passages of Lorem Ipsum available, but the majority have suffered alteration in some form, by injected humour, or randomised words which dont look even slightly believable There are many variations of passages of Lorem Ipsum available, but the majority have suffered alteration in some form, by injected humour.</p>', 'Koala_kumal.jpg', '0');
INSERT INTO `berita` VALUES ('88', '1995-09-16', 'molestiae', '<p>There are many variations of passages of Lorem Ipsum available, but the majority have suffered alteration in some form, by injected humour, or randomised words which dont look even slightly believable There are many variations of passages of Lorem Ipsum available, but the majority have suffered alteration in some form, by injected humour.</p>', 'Koala_kumal.jpg', '0');
INSERT INTO `berita` VALUES ('89', '1978-03-21', 'ipsum', '<p>There are many variations of passages of Lorem Ipsum available, but the majority have suffered alteration in some form, by injected humour, or randomised words which dont look even slightly believable There are many variations of passages of Lorem Ipsum available, but the majority have suffered alteration in some form, by injected humour.</p>', 'Koala_kumal.jpg', '0');
INSERT INTO `berita` VALUES ('90', '2018-02-13', 'ex', '<p>There are many variations of passages of Lorem Ipsum available, but the majority have suffered alteration in some form, by injected humour, or randomised words which dont look even slightly believable There are many variations of passages of Lorem Ipsum available, but the majority have suffered alteration in some form, by injected humour.</p>', 'Koala_kumal.jpg', '0');
INSERT INTO `berita` VALUES ('91', '1994-07-20', 'repellat', '<p>There are many variations of passages of Lorem Ipsum available, but the majority have suffered alteration in some form, by injected humour, or randomised words which dont look even slightly believable There are many variations of passages of Lorem Ipsum available, but the majority have suffered alteration in some form, by injected humour.</p>', 'Koala_kumal.jpg', '0');
INSERT INTO `berita` VALUES ('92', '1982-05-17', 'eligendi', '<p>There are many variations of passages of Lorem Ipsum available, but the majority have suffered alteration in some form, by injected humour, or randomised words which dont look even slightly believable There are many variations of passages of Lorem Ipsum available, but the majority have suffered alteration in some form, by injected humour.</p>', 'Koala_kumal.jpg', '0');
INSERT INTO `berita` VALUES ('93', '1974-01-11', 'cumque', '<p>There are many variations of passages of Lorem Ipsum available, but the majority have suffered alteration in some form, by injected humour, or randomised words which dont look even slightly believable There are many variations of passages of Lorem Ipsum available, but the majority have suffered alteration in some form, by injected humour.</p>', 'Koala_kumal.jpg', '0');
INSERT INTO `berita` VALUES ('94', '1990-07-29', 'nemo', '<p>There are many variations of passages of Lorem Ipsum available, but the majority have suffered alteration in some form, by injected humour, or randomised words which dont look even slightly believable There are many variations of passages of Lorem Ipsum available, but the majority have suffered alteration in some form, by injected humour.</p>', 'Koala_kumal.jpg', '0');
INSERT INTO `berita` VALUES ('95', '1995-06-03', 'aut', '<p>There are many variations of passages of Lorem Ipsum available, but the majority have suffered alteration in some form, by injected humour, or randomised words which dont look even slightly believable There are many variations of passages of Lorem Ipsum available, but the majority have suffered alteration in some form, by injected humour.</p>', 'Koala_kumal.jpg', '0');
INSERT INTO `berita` VALUES ('96', '1999-02-24', 'aut', '<p>There are many variations of passages of Lorem Ipsum available, but the majority have suffered alteration in some form, by injected humour, or randomised words which dont look even slightly believable There are many variations of passages of Lorem Ipsum available, but the majority have suffered alteration in some form, by injected humour.</p>', 'Koala_kumal.jpg', '0');
INSERT INTO `berita` VALUES ('97', '1991-03-09', 'aliquid', '<p>There are many variations of passages of Lorem Ipsum available, but the majority have suffered alteration in some form, by injected humour, or randomised words which dont look even slightly believable There are many variations of passages of Lorem Ipsum available, but the majority have suffered alteration in some form, by injected humour.</p>', 'Koala_kumal.jpg', '0');
INSERT INTO `berita` VALUES ('98', '2003-09-14', 'et', '<p>There are many variations of passages of Lorem Ipsum available, but the majority have suffered alteration in some form, by injected humour, or randomised words which dont look even slightly believable There are many variations of passages of Lorem Ipsum available, but the majority have suffered alteration in some form, by injected humour.</p>', 'Koala_kumal.jpg', '0');
INSERT INTO `berita` VALUES ('99', '2006-01-18', 'asperiores', '<p>There are many variations of passages of Lorem Ipsum available, but the majority have suffered alteration in some form, by injected humour, or randomised words which dont look even slightly believable There are many variations of passages of Lorem Ipsum available, but the majority have suffered alteration in some form, by injected humour.</p>', 'Koala_kumal.jpg', '0');
INSERT INTO `berita` VALUES ('100', '2014-04-14', 'accusamus', '<p>There are many variations of passages of Lorem Ipsum available, but the majority have suffered alteration in some form, by injected humour, or randomised words which dont look even slightly believable There are many variations of passages of Lorem Ipsum available, but the majority have suffered alteration in some form, by injected humour.</p>', 'Koala_kumal.jpg', '0');
INSERT INTO `berita` VALUES ('101', '1986-08-23', 'corporis', '<p>There are many variations of passages of Lorem Ipsum available, but the majority have suffered alteration in some form, by injected humour, or randomised words which dont look even slightly believable There are many variations of passages of Lorem Ipsum available, but the majority have suffered alteration in some form, by injected humour.</p>', 'Koala_kumal.jpg', '0');
INSERT INTO `berita` VALUES ('102', '1982-11-21', 'vitae', '<p>There are many variations of passages of Lorem Ipsum available, but the majority have suffered alteration in some form, by injected humour, or randomised words which dont look even slightly believable There are many variations of passages of Lorem Ipsum available, but the majority have suffered alteration in some form, by injected humour.</p>', 'Koala_kumal.jpg', '0');
INSERT INTO `berita` VALUES ('103', '1986-08-29', 'quidem', '<p>There are many variations of passages of Lorem Ipsum available, but the majority have suffered alteration in some form, by injected humour, or randomised words which dont look even slightly believable There are many variations of passages of Lorem Ipsum available, but the majority have suffered alteration in some form, by injected humour.</p>', 'Koala_kumal.jpg', '0');
INSERT INTO `berita` VALUES ('104', '1997-08-21', 'dolores', '<p>There are many variations of passages of Lorem Ipsum available, but the majority have suffered alteration in some form, by injected humour, or randomised words which dont look even slightly believable There are many variations of passages of Lorem Ipsum available, but the majority have suffered alteration in some form, by injected humour.</p>', 'Koala_kumal.jpg', '0');
INSERT INTO `berita` VALUES ('105', '1974-05-28', 'ratione', '<p>There are many variations of passages of Lorem Ipsum available, but the majority have suffered alteration in some form, by injected humour, or randomised words which dont look even slightly believable There are many variations of passages of Lorem Ipsum available, but the majority have suffered alteration in some form, by injected humour.</p>', 'Koala_kumal.jpg', '0');
INSERT INTO `berita` VALUES ('106', '1992-06-20', 'aliquid', '<p>There are many variations of passages of Lorem Ipsum available, but the majority have suffered alteration in some form, by injected humour, or randomised words which dont look even slightly believable There are many variations of passages of Lorem Ipsum available, but the majority have suffered alteration in some form, by injected humour.</p>', 'Koala_kumal.jpg', '0');
INSERT INTO `berita` VALUES ('107', '1976-01-25', 'non', '<p>There are many variations of passages of Lorem Ipsum available, but the majority have suffered alteration in some form, by injected humour, or randomised words which dont look even slightly believable There are many variations of passages of Lorem Ipsum available, but the majority have suffered alteration in some form, by injected humour.</p>', 'Koala_kumal.jpg', '0');
INSERT INTO `berita` VALUES ('108', '1994-06-12', 'eos', '<p>There are many variations of passages of Lorem Ipsum available, but the majority have suffered alteration in some form, by injected humour, or randomised words which dont look even slightly believable There are many variations of passages of Lorem Ipsum available, but the majority have suffered alteration in some form, by injected humour.</p>', 'Koala_kumal.jpg', '0');
INSERT INTO `berita` VALUES ('109', '2007-03-08', 'nisi', '<p>There are many variations of passages of Lorem Ipsum available, but the majority have suffered alteration in some form, by injected humour, or randomised words which dont look even slightly believable There are many variations of passages of Lorem Ipsum available, but the majority have suffered alteration in some form, by injected humour.</p>', 'Koala_kumal.jpg', '0');
INSERT INTO `berita` VALUES ('110', '2013-01-05', 'unde', '<p>There are many variations of passages of Lorem Ipsum available, but the majority have suffered alteration in some form, by injected humour, or randomised words which dont look even slightly believable There are many variations of passages of Lorem Ipsum available, but the majority have suffered alteration in some form, by injected humour.</p>', 'Koala_kumal.jpg', '0');
INSERT INTO `berita` VALUES ('111', '2003-07-10', 'ullam', '<p>There are many variations of passages of Lorem Ipsum available, but the majority have suffered alteration in some form, by injected humour, or randomised words which dont look even slightly believable There are many variations of passages of Lorem Ipsum available, but the majority have suffered alteration in some form, by injected humour.</p>', 'Koala_kumal.jpg', '0');
INSERT INTO `berita` VALUES ('112', '2007-03-20', 'nulla', '<p>There are many variations of passages of Lorem Ipsum available, but the majority have suffered alteration in some form, by injected humour, or randomised words which dont look even slightly believable There are many variations of passages of Lorem Ipsum available, but the majority have suffered alteration in some form, by injected humour.</p>', 'Koala_kumal.jpg', '0');
INSERT INTO `berita` VALUES ('113', '1992-12-06', 'tenetur', '<p>There are many variations of passages of Lorem Ipsum available, but the majority have suffered alteration in some form, by injected humour, or randomised words which dont look even slightly believable There are many variations of passages of Lorem Ipsum available, but the majority have suffered alteration in some form, by injected humour.</p>', 'Koala_kumal.jpg', '0');
INSERT INTO `berita` VALUES ('114', '1970-06-02', 'blanditiis', '<p>There are many variations of passages of Lorem Ipsum available, but the majority have suffered alteration in some form, by injected humour, or randomised words which dont look even slightly believable There are many variations of passages of Lorem Ipsum available, but the majority have suffered alteration in some form, by injected humour.</p>', 'Koala_kumal.jpg', '0');
INSERT INTO `berita` VALUES ('115', '1975-02-26', 'culpa', '<p>There are many variations of passages of Lorem Ipsum available, but the majority have suffered alteration in some form, by injected humour, or randomised words which dont look even slightly believable There are many variations of passages of Lorem Ipsum available, but the majority have suffered alteration in some form, by injected humour.</p>', 'Koala_kumal.jpg', '0');
INSERT INTO `berita` VALUES ('116', '1988-05-06', 'nemo', '<p>There are many variations of passages of Lorem Ipsum available, but the majority have suffered alteration in some form, by injected humour, or randomised words which dont look even slightly believable There are many variations of passages of Lorem Ipsum available, but the majority have suffered alteration in some form, by injected humour.</p>', 'Koala_kumal.jpg', '0');
INSERT INTO `berita` VALUES ('117', '2000-06-09', 'maiores', '<p>There are many variations of passages of Lorem Ipsum available, but the majority have suffered alteration in some form, by injected humour, or randomised words which dont look even slightly believable There are many variations of passages of Lorem Ipsum available, but the majority have suffered alteration in some form, by injected humour.</p>', 'Koala_kumal.jpg', '0');
INSERT INTO `berita` VALUES ('118', '1976-04-18', 'est', '<p>There are many variations of passages of Lorem Ipsum available, but the majority have suffered alteration in some form, by injected humour, or randomised words which dont look even slightly believable There are many variations of passages of Lorem Ipsum available, but the majority have suffered alteration in some form, by injected humour.</p>', 'Koala_kumal.jpg', '0');
INSERT INTO `berita` VALUES ('119', '1994-10-28', 'dolores', '<p>There are many variations of passages of Lorem Ipsum available, but the majority have suffered alteration in some form, by injected humour, or randomised words which dont look even slightly believable There are many variations of passages of Lorem Ipsum available, but the majority have suffered alteration in some form, by injected humour.</p>', 'Koala_kumal.jpg', '0');
INSERT INTO `berita` VALUES ('120', '1997-01-27', 'laborum', '<p>There are many variations of passages of Lorem Ipsum available, but the majority have suffered alteration in some form, by injected humour, or randomised words which dont look even slightly believable There are many variations of passages of Lorem Ipsum available, but the majority have suffered alteration in some form, by injected humour.</p>', 'Koala_kumal.jpg', '0');
INSERT INTO `berita` VALUES ('121', '2015-03-25', 'corporis', '<p>There are many variations of passages of Lorem Ipsum available, but the majority have suffered alteration in some form, by injected humour, or randomised words which dont look even slightly believable There are many variations of passages of Lorem Ipsum available, but the majority have suffered alteration in some form, by injected humour.</p>', 'Koala_kumal.jpg', '0');
INSERT INTO `berita` VALUES ('122', '1980-12-04', 'quidem', '<p>There are many variations of passages of Lorem Ipsum available, but the majority have suffered alteration in some form, by injected humour, or randomised words which dont look even slightly believable There are many variations of passages of Lorem Ipsum available, but the majority have suffered alteration in some form, by injected humour.</p>', 'Koala_kumal.jpg', '0');
INSERT INTO `berita` VALUES ('123', '2006-09-20', 'culpa', '<p>There are many variations of passages of Lorem Ipsum available, but the majority have suffered alteration in some form, by injected humour, or randomised words which dont look even slightly believable There are many variations of passages of Lorem Ipsum available, but the majority have suffered alteration in some form, by injected humour.</p>', 'Koala_kumal.jpg', '0');
INSERT INTO `berita` VALUES ('124', '2004-07-24', 'ab', '<p>There are many variations of passages of Lorem Ipsum available, but the majority have suffered alteration in some form, by injected humour, or randomised words which dont look even slightly believable There are many variations of passages of Lorem Ipsum available, but the majority have suffered alteration in some form, by injected humour.</p>', 'Koala_kumal.jpg', '0');
INSERT INTO `berita` VALUES ('125', '1976-04-02', 'autem', '<p>There are many variations of passages of Lorem Ipsum available, but the majority have suffered alteration in some form, by injected humour, or randomised words which dont look even slightly believable There are many variations of passages of Lorem Ipsum available, but the majority have suffered alteration in some form, by injected humour.</p>', 'Koala_kumal.jpg', '0');
INSERT INTO `berita` VALUES ('126', '1990-01-23', 'est', '<p>There are many variations of passages of Lorem Ipsum available, but the majority have suffered alteration in some form, by injected humour, or randomised words which dont look even slightly believable There are many variations of passages of Lorem Ipsum available, but the majority have suffered alteration in some form, by injected humour.</p>', 'Koala_kumal.jpg', '0');
INSERT INTO `berita` VALUES ('127', '2002-05-23', 'unde', '<p>There are many variations of passages of Lorem Ipsum available, but the majority have suffered alteration in some form, by injected humour, or randomised words which dont look even slightly believable There are many variations of passages of Lorem Ipsum available, but the majority have suffered alteration in some form, by injected humour.</p>', 'Koala_kumal.jpg', '0');
INSERT INTO `berita` VALUES ('128', '1993-06-25', 'nemo', '<p>There are many variations of passages of Lorem Ipsum available, but the majority have suffered alteration in some form, by injected humour, or randomised words which dont look even slightly believable There are many variations of passages of Lorem Ipsum available, but the majority have suffered alteration in some form, by injected humour.</p>', 'Koala_kumal.jpg', '0');
INSERT INTO `berita` VALUES ('129', '1974-09-19', 'quia', '<p>There are many variations of passages of Lorem Ipsum available, but the majority have suffered alteration in some form, by injected humour, or randomised words which dont look even slightly believable There are many variations of passages of Lorem Ipsum available, but the majority have suffered alteration in some form, by injected humour.</p>', 'Koala_kumal.jpg', '0');
INSERT INTO `berita` VALUES ('130', '1976-06-26', 'sed', '<p>There are many variations of passages of Lorem Ipsum available, but the majority have suffered alteration in some form, by injected humour, or randomised words which dont look even slightly believable There are many variations of passages of Lorem Ipsum available, but the majority have suffered alteration in some form, by injected humour.</p>', 'Koala_kumal.jpg', '0');
INSERT INTO `berita` VALUES ('131', '1972-04-28', 'ut', '<p>There are many variations of passages of Lorem Ipsum available, but the majority have suffered alteration in some form, by injected humour, or randomised words which dont look even slightly believable There are many variations of passages of Lorem Ipsum available, but the majority have suffered alteration in some form, by injected humour.</p>', 'Koala_kumal.jpg', '0');
INSERT INTO `berita` VALUES ('132', '1984-04-10', 'nulla', '<p>There are many variations of passages of Lorem Ipsum available, but the majority have suffered alteration in some form, by injected humour, or randomised words which dont look even slightly believable There are many variations of passages of Lorem Ipsum available, but the majority have suffered alteration in some form, by injected humour.</p>', 'Koala_kumal.jpg', '0');
INSERT INTO `berita` VALUES ('133', '2006-06-14', 'iste', '<p>There are many variations of passages of Lorem Ipsum available, but the majority have suffered alteration in some form, by injected humour, or randomised words which dont look even slightly believable There are many variations of passages of Lorem Ipsum available, but the majority have suffered alteration in some form, by injected humour.</p>', 'Koala_kumal.jpg', '0');
INSERT INTO `berita` VALUES ('134', '1995-07-23', 'cupiditate', '<p>There are many variations of passages of Lorem Ipsum available, but the majority have suffered alteration in some form, by injected humour, or randomised words which dont look even slightly believable There are many variations of passages of Lorem Ipsum available, but the majority have suffered alteration in some form, by injected humour.</p>', 'Koala_kumal.jpg', '0');
INSERT INTO `berita` VALUES ('135', '2008-10-10', 'vel', '<p>There are many variations of passages of Lorem Ipsum available, but the majority have suffered alteration in some form, by injected humour, or randomised words which dont look even slightly believable There are many variations of passages of Lorem Ipsum available, but the majority have suffered alteration in some form, by injected humour.</p>', 'Koala_kumal.jpg', '0');
INSERT INTO `berita` VALUES ('136', '1999-12-03', 'architecto', '<p>There are many variations of passages of Lorem Ipsum available, but the majority have suffered alteration in some form, by injected humour, or randomised words which dont look even slightly believable There are many variations of passages of Lorem Ipsum available, but the majority have suffered alteration in some form, by injected humour.</p>', 'Koala_kumal.jpg', '0');
INSERT INTO `berita` VALUES ('137', '1990-08-23', 'ullam', '<p>There are many variations of passages of Lorem Ipsum available, but the majority have suffered alteration in some form, by injected humour, or randomised words which dont look even slightly believable There are many variations of passages of Lorem Ipsum available, but the majority have suffered alteration in some form, by injected humour.</p>', 'Koala_kumal.jpg', '0');

-- ----------------------------
-- Table structure for gallery
-- ----------------------------
DROP TABLE IF EXISTS `gallery`;
CREATE TABLE `gallery` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `caption` varchar(255) DEFAULT NULL,
  `tanggal` date DEFAULT NULL,
  `image` varchar(255) DEFAULT NULL,
  `aktif` int(11) DEFAULT 0,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=19 DEFAULT CHARSET=latin1;

-- ----------------------------
-- Records of gallery
-- ----------------------------
INSERT INTO `gallery` VALUES ('9', 'Kerja Bakti', '2019-10-04', 'kerja_bakti.jpg', '0');
INSERT INTO `gallery` VALUES ('15', 'Penyuluhan', '2019-10-09', 'penyuluhan.jpg', '1');
INSERT INTO `gallery` VALUES ('16', 'Senam Bersama', '2019-10-06', 'senam.jpg', '0');
INSERT INTO `gallery` VALUES ('17', 'Syukuran Desa', '2019-10-06', 'syukuran.jpg', '0');
INSERT INTO `gallery` VALUES ('18', 'Penyerahan PAMSIMAS', '2019-10-07', 'pamsimas.jpg', '0');
